const express = require('express')
const routerProduct = require('./router/product')
const bodyParser = require('body-parser')
const cors = require('cors')
const sequelize = require('./util/dataBase')
const app = express()
app.use(cors())
app.use(bodyParser.json())
app.use('/', routerProduct)
sequelize.sync().then(()=>{
    app.listen(3000)
}).catch(err=>console.log(err))
sequelize.sync()